export const VISION = "AT MY DETAILING, WE BELIEVE YOUR VEHICLE DESERVES MORE THAN JUST A WASH." + 
    "OUR EXPERT SERVICES REJUVENATE, PROTECT, AND ELEVATE YOUR" +
    "VEHICLE’S APPEARANCE, INSIDE AND OUT. WITH PREMIUM PRODUCTS AND" +
    "METICULOUS CARE, WE DELIVER RESULTS THAT EMBODY TRUE CRAFTSMANSHIP.";

export const SLOGAN = "We Clean You Shine";

export const TITLE = "MY Detailing";

export const SUBTITLE = "Premium Car Detailing in Winkler!"